package br.edu.ifg.luziania.sad.api.enums;

public enum TipoEnum {
	AVALIACAO_ALUNO,
	AUTO_AVALIACAO,
	AVALIACAO_SUPERIOR

	/*INICIO_TRABALHO,
	INICIO_ALMOCO,
	TERMINO_ALMOCO,
	INICIO_PAUSA,
	TERMINO_PAUSA,
	TERMINO_TRABALHO*/
}
